const CONFIG = {
  businessName: "Your Business Name",
  niche: "Home Services",
  tagline: "Reliable local service, done right.",
  phone: "(555) 010-0200", phoneRaw: "5550100200", email: "hello@yourbusiness.com",
  city: "Your City", state: "Your State", stateShort: "ST", address: "", licenseNumber: "",
  colors: { primary: "#2563EB", secondary: "#1C2333" },
  social: { facebook: "", instagram: "", youtube: "", yelp: "", nextdoor: "" },
  googleReviewsUrl: "", rating: "5.0", reviewCount: 0, yearsExperience: 0,
  projectsCompleted: "100+", satisfactionRate: "98%",
  webhookUrl: "", metaPixelId: "",
  hero: {
    headline: "Reliable home service, built around your needs.",
    subheadline: "Clear communication, dependable scheduling, and professional work from a local team.",
    ctaPrimary: "Get a Free Estimate", ctaSecondary: "See Our Work",
    heroImage: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=1200&q=75&fm=webp&auto=format",
  },
  services: [{
    slug: "consultation-estimates", name: "Consultation & Estimates",
    desc: "Clear recommendations and no-pressure estimates for your project.",
    image: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=800&q=75&fm=webp&auto=format",
    longDesc: "We start by understanding your property, priorities, and timeline, then provide a clear recommendation and written estimate before any work begins.",
    benefits: ["Clear scope of work", "Up-front pricing", "Helpful expert guidance"],
    faqs: [{ q: "How do I get started?", a: "Contact us to schedule a convenient consultation and estimate." }],
  }],
  maps: { mapEmbedUrl: "", mapSearchQuery: "Your City ST home services", mapHeight: 420 },
  serviceAreas: [{ slug: "your-city", name: "Your City", county: "" }],
  testimonials: [],
  processSteps: [
    { title: "Tell Us About Your Project", desc: "Share your goals and schedule a convenient consultation." },
    { title: "Receive a Clear Plan", desc: "We assess the work and provide a straightforward recommendation." },
    { title: "Professional Service", desc: "Our team completes the job with care and clear communication." },
    { title: "Final Walkthrough", desc: "We make sure the completed work meets your expectations." },
  ],
  faqs: [], portfolioProjects: [],
  legal: { privacyPolicyDate: "May 1, 2025", termsDate: "May 1, 2025" },
};
