const CONFIG = {
  businessName: "Elite Glass & Window",
  niche: "Glass & Window",
  tagline: "Your Trusted Partner for Premium Glass & Window Solutions in Seattle",
  phone: "425-890-8233",
  phoneRaw: "4258908233",
  email: "sales@eliteglassandwindow.com",
  city: "Seattle",
  state: "Washington",
  stateShort: "WA",
  address: "",
  licenseNumber: "",
  colors: { primary: "#004080", secondary: "#1C2333" },
  social: { facebook: "", instagram: "", youtube: "", yelp: "", nextdoor: "" },
  googleReviewsUrl: "https://search.google.com/local/writereview?placeid=ChIJg31wD_9tkFQRp-As1RijQDA",
  rating: "4.8",
  reviewCount: 42,
  yearsExperience: 0,
  projectsCompleted: "0+",
  satisfactionRate: "98%",
  webhookUrl: "",
  metaPixelId: "",
  maps: { mapEmbedUrl: "", mapSearchQuery: "Elite Glass & Window Redmond WA", mapHeight: 420 },
  hero: {
    eyebrow: "Local Home Service Professionals",
    headline: "Transform Your Home with Elite Glass & Window Solutions",
    subheadline: "Enhancing Homes and Businesses with Quality Craftsmanship and Unmatched Service Across the Greater Seattle Area.",
    ctaPrimary: "Get a Free Estimate",
    ctaSecondary: "Explore Services",
    heroImage: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=1600&q=80&auto=format&fit=crop",
  },
  services: [
    {
      slug: "window-replacement",
      name: "Window Replacement & Installation",
      desc: "Upgrade your home with energy-efficient window replacement and new window installations.",
      longDesc: "Whether you're looking to replace old, inefficient windows or install new ones in a construction project, we offer a comprehensive selection of high-quality windows designed for durability, energy efficiency, and aesthetic appeal. Choose from various styles, including vinyl, wood, and aluminum.",
      benefits: ["Increased energy efficiency", "Reduced noise pollution", "Improved home comfort", "Modernized appearance", "Custom fit and finish"],
      faqs: [
        { q: "How long does window replacement take?", a: "The timeline depends on the number and type of windows, but most residential projects are completed within a few days." },
        { q: "What types of windows do you install?", a: "We install a wide range of window types, including single-hung, double-hung, casement, awning, picture, slider, bay, and bow windows." }
      ],
      image: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=1000&q=80&auto=format&fit=crop",
    },
    {
      slug: "shower-doors",
      name: "Shower Doors",
      desc: "Custom frameless and sliding shower doors for a modern bathroom.",
      longDesc: "Transform your bathroom with our exquisite custom shower doors, including frameless, semi-frameless, and sliding options. We offer a variety of glass types and hardware finishes to match your style, ensuring a luxurious and functional upgrade.",
      benefits: ["Modern aesthetic", "Custom design options", "Enhanced bathroom functionality", "Durable, high-quality glass", "Easy to clean"],
      faqs: [
        { q: "What types of shower doors do you offer?", a: "We specialize in frameless, semi-frameless, and sliding shower doors, available in various glass thicknesses and finishes." },
        { q: "Can you install a custom-sized shower door?", a: "Yes, all our shower doors are custom measured and installed to perfectly fit your unique shower opening." }
      ],
      image: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=1000&q=80&auto=format&fit=crop",
    },
    {
      slug: "entry-patio-doors",
      name: "Entry & Patio Doors",
      desc: "Enhance your home's curb appeal and security with our premium door installations.",
      longDesc: "From elegant entry doors that make a statement to functional and beautiful patio doors that connect your indoor and outdoor spaces, we provide expert installation of a wide range of door styles and materials, including wood, fiberglass, and steel.",
      benefits: ["Improved home security", "Enhanced energy efficiency", "Boosted curb appeal", "Variety of styles and materials", "Professional installation"],
      faqs: [
        { q: "Can you help me choose the right door for my home?", a: "Absolutely! Our experts will guide you through the selection process, considering your home's style, budget, and functional needs." },
        { q: "Do you install interior doors as well?", a: "While our primary focus is exterior entry and patio doors, we can discuss interior door projects based on your specific needs." }
      ],
      image: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=1000&q=80&auto=format&fit=crop",
    },
    {
      slug: "glass-railings",
      name: "Glass Railings",
      desc: "Modern and elegant glass railings for decks, balconies, and staircases.",
      longDesc: "Our glass railing systems provide a contemporary and unobstructed view for your deck, balcony, or interior stairs. Engineered for safety and durability, these railings add a touch of sophistication while maximizing natural light and openness.",
      benefits: ["Unobstructed views", "Modern aesthetic", "Enhanced safety and durability", "Low maintenance", "Increases property value"],
      faqs: [
        { q: "Are glass railings safe?", a: "Yes, our glass railings are constructed with tempered safety glass and robust hardware, meeting all local building codes for safety and structural integrity." },
        { q: "What is the maintenance for glass railings?", a: "Glass railings are relatively low maintenance. Regular cleaning with glass cleaner is usually sufficient to keep them looking pristine." }
      ],
      image: "https://images.unsplash.com/photo-1581578731548-c64696cc6952?w=1000&q=80&auto=format&fit=crop",
    },
    {
      slug: "custom-mirrors",
      name: "Custom Mirrors",
      desc: "Beautiful custom-cut mirrors for vanities, walls, gyms, and more.",
      longDesc: "Add light, space, and style to any room with our custom mirror services. We design, cut, and install mirrors for bathrooms, gyms, living areas, and commercial spaces, offering various edges, tints, and sizes to perfectly fit your vision.",
      benefits: ["Custom-fit to any space", "Enhances room brightness", "Creates illusion of space", "Variety of edge finishes", "Professional installation"],
      faqs: [
        { q: "Can you install a large mirror?", a: "Yes, we specialize in installing large wall mirrors for homes, gyms, and commercial applications, ensuring secure and precise placement." },
        { q: "What types of mirror edges do you offer?", a: "We offer various edge finishes, including polished, beveled, and seamed edges, to complement your design aesthetic." }
      ],
      image: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=1000&q=80&auto=format&fit=crop",
    },
    {
      slug: "storefront-glass",
      name: "Storefront Glass",
      desc: "Professional storefront glass installation and repair for businesses.",
      longDesc: "Make a lasting first impression with our high-quality storefront glass solutions. We provide expert installation, repair, and replacement of commercial glass, including impact-resistant options, to enhance your business's appearance and security.",
      benefits: ["Improved business aesthetic", "Enhanced security", "Custom design options", "Quick repair services", "Energy-efficient solutions"],
      faqs: [
        { q: "Do you offer emergency storefront glass repair?", a: "Yes, we provide emergency repair services to secure your business quickly and efficiently after breakage." },
        { q: "Can you install custom logos or branding on storefront glass?", a: "We can work with your design specifications for custom branding or signage integration on your storefront glass." }
      ],
      image: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=1000&q=80&auto=format&fit=crop",
    },
    {
      slug: "glass-replacement",
      name: "Glass Replacement",
      desc: "Expert glass replacement services for windows, doors, and more.",
      longDesc: "Whether it's a cracked window, a foggy insulated glass unit, or a broken door panel, our skilled technicians provide prompt and reliable glass replacement services. We match existing glass types and ensure a seamless, high-quality repair.",
      benefits: ["Restores clarity and integrity", "Prevents further damage", "Energy efficiency improvement", "Professional, timely service", "Cost-effective solution"],
      faqs: [
        { q: "Can you replace just one pane of glass in a double-pane window?", a: "Yes, in most cases, we can replace just the insulated glass unit (IGU) without needing to replace the entire window frame." },
        { q: "What types of glass can you replace?", a: "We replace various types of glass, including single-pane, double-pane (IGUs), tempered, laminated, and specialty glass for residential and commercial applications." }
      ],
      image: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=1000&q=80&auto=format&fit=crop",
    },
  ],
  serviceAreas: [
    { slug: "redmond", name: "Redmond", county: "" },
    { slug: "bellevue", name: "Bellevue", county: "" },
    { slug: "kirkland", name: "Kirkland", county: "" },
    { slug: "sammamish", name: "Sammamish", county: "" },
    { slug: "issaquah", name: "Issaquah", county: "" },
    { slug: "mercer-island", name: "Mercer Island", county: "" },
    { slug: "newcastle", name: "Newcastle", county: "" },
    { slug: "woodinville", name: "Woodinville", county: "" },
    { slug: "bothell", name: "Bothell", county: "" },
    { slug: "kenmore", name: "Kenmore", county: "" },
    { slug: "duvall", name: "Duvall", county: "" },
    { slug: "snoqualmie", name: "Snoqualmie", county: "" },
    { slug: "north-bend", name: "North Bend", county: "" },
    { slug: "shoreline", name: "Shoreline", county: "" },
    { slug: "edmonds", name: "Edmonds", county: "" },
    { slug: "lynnwood", name: "Lynnwood", county: "" },
    { slug: "mountlake-terrace", name: "Mountlake Terrace", county: "" },
    { slug: "mill-creek", name: "Mill Creek", county: "" },
    { slug: "everett", name: "Everett", county: "" },
    { slug: "mukilteo", name: "Mukilteo", county: "" },
    { slug: "renton", name: "Renton", county: "" },
    { slug: "kent", name: "Kent", county: "" },
    { slug: "auburn", name: "Auburn", county: "" },
    { slug: "tukwila", name: "Tukwila", county: "" },
    { slug: "federal-way", name: "Federal Way", county: "" },
    { slug: "burien", name: "Burien", county: "" },
    { slug: "seatac", name: "SeaTac", county: "" },
    { slug: "des-moines", name: "Des Moines", county: "" },
    { slug: "seattle", name: "Seattle", county: "" },
    { slug: "west-seattle", name: "West Seattle", county: "" },
    { slug: "ballard", name: "Ballard", county: "" },
    { slug: "queen-anne", name: "Queen Anne", county: "" },
    { slug: "capitol-hill", name: "Capitol Hill", county: "" },
    { slug: "magnolia", name: "Magnolia", county: "" },
    { slug: "green-lake", name: "Green Lake", county: "" },
    { slug: "university-district", name: "University District", county: "" },
    { slug: "mercer-island", name: "Mercer Island", county: "" },
    { slug: "bainbridge-island", name: "Bainbridge Island", county: "" }
  ],
  testimonials: [
    { name: "Sarah", review: "Elite Glass & Window did an amazing job replacing our old, drafty windows in our Seattle home. The team was professional, efficient, and the new windows look fantastic and have made a huge difference in our energy bills!" },
    { name: "David", review: "We absolutely love our new frameless shower door from Elite Glass & Window. The installation was flawless, and it completely transformed our bathroom. Highly recommend their services in Seattle!" },
    { name: "Emily", review: "When our storefront window was vandalized, Elite Glass & Window responded quickly and had it replaced in no time. Their emergency service in Seattle saved us a lot of stress and potential business loss." },
    { name: "Michael", review: "The custom mirrors they installed in our Seattle gym studio are perfect! Elite Glass & Window provided excellent service from consultation to installation. Very happy with the quality and professionalism." },
  ],
  processSteps: [
    { title: "Tell Us About Your Project", desc: "Share your goals and schedule a convenient consultation." },
    { title: "Receive a Clear Plan", desc: "We assess the work and provide a straightforward recommendation." },
    { title: "Professional Service", desc: "Our team completes the job with care and clear communication." },
    { title: "Final Walkthrough", desc: "We make sure the completed work meets your expectations." },
  ],
  faqs: [
    { q: "What areas do you serve?", a: "We proudly serve Seattle and the surrounding Puget Sound region, including Redmond, Bellevue, Kirkland, and many other communities listed in our service areas." },
    { q: "Do you offer free estimates?", a: "Yes, we provide free, no-obligation estimates for all our glass and window services. Contact us to schedule an appointment." },
    { q: "How long does a typical installation take?", a: "Installation times vary depending on the scope of the project. A single window replacement might take a few hours, while a full home window replacement or custom shower door could take a day or more. We'll provide an estimated timeline during your consultation." },
    { q: "What kind of warranty do you offer on your work?", a: "We stand by the quality of our workmanship and the products we install. Warranties vary by product and service; please ask for specific details during your consultation." },
    { q: "Do you handle both residential and commercial projects?", a: "Yes, Elite Glass & Window is equipped to handle both residential and commercial glass and window projects, from home window replacements to storefront installations." },
    { q: "What payment options do you accept?", a: "We accept various payment methods, including major credit cards, checks, and financing options for larger projects. Please discuss payment details with our team." },
    { q: "Can you help with custom glass projects?", a: "Absolutely! We specialize in custom glass solutions, including unique mirror designs, glass tabletops, and specialty glass installations. Bring us your vision!" },
    { q: "Are your technicians licensed and insured?", a: "Yes, all our technicians are highly trained, experienced, and fully insured for your peace of mind and protection." }
  ],
  portfolioProjects: [],
  legal: { privacyPolicyDate: "May 1, 2025", termsDate: "May 1, 2025" },
};