// Verified Elite Glass & Window case studies and photography.
// Keep this file as the single content source for the home-page teaser and
// the full Our Work page. Every image is stored locally under /public/projects.
const PROJECTS = [
  {
    id: "storefront-glass-replacement-bothell",
    title: "Storefront Glass Replacement in Bothell, WA",
    category: "Commercial Glass",
    location: "Bothell, WA",
    completed: "May 2024",
    duration: "2 Hours",
    tagline: "Fast Service. Clear Results.",
    summary: "We replaced one broken storefront glass panel with new tempered glass to restore safety, security, and the professional appearance of the business.",
    overview: "A customer's storefront glass panel was accidentally damaged. We responded the same day, removed the broken glass, and installed a new tempered glass panel to restore the safety and appearance of the storefront.",
    benefitHeading: "Benefits for the Business",
    benefits: ["Restores safety and security", "Improves curb appeal", "Clear visibility for customers", "Minimizes business interruption"],
    details: [
      { label: "Glass Type", value: "1/2-inch tempered clear glass" },
      { label: "System", value: "Storefront framing system" },
      { label: "Color", value: "Clear" },
      { label: "Location", value: "Bothell, WA" },
      { label: "Scope", value: "Glass replacement, 1 panel" },
      { label: "Warranty", value: "1-year workmanship warranty" },
    ],
    features: ["1/2-inch tempered glass for safety", "Matches the existing storefront system", "Professional installation completed the same day", "Clean and secure finish"],
    img: "/public/projects/storefront.jpg",
    alt: "Damaged storefront glass before replacement in Bothell, Washington",
    width: 1392,
    height: 1014,
    featured: true,
    sourceUrl: "https://eliteglassandwindow.com/elite/projects/storefront-glass-replacement-in-bothell--wa/",
    process: [
      { stage: "Before", img: "/public/projects/storefront_1.jpg", alt: "Broken storefront glass before replacement", width: 586, height: 488 },
      { stage: "During Replacement", img: "/public/projects/storefront_2.jpg", alt: "Storefront glass panel during replacement", width: 586, height: 488 },
      { stage: "After", img: "/public/projects/storefront_3.jpg", alt: "Storefront after the new tempered glass panel was installed", width: 586, height: 488 },
    ],
    related: [
      { title: "Glass Replacement in Seattle, WA", img: "/public/projects/storefront_4.jpg", alt: "Commercial glass replacement project in Seattle", width: 462, height: 206 },
      { title: "Corner Shower Enclosure in Kirkland, WA", img: "/public/projects/storefront_5.jpg", alt: "Corner shower enclosure project in Kirkland", width: 464, height: 204 },
      { title: "Glass Replacement in Renton, WA", img: "/public/projects/storefront_6.jpg", alt: "Commercial glass replacement project in Renton", width: 460, height: 206 },
      { title: "Glass Replacement in Lynnwood, WA", img: "/public/projects/storefront_7.jpg", alt: "Commercial glass replacement project in Lynnwood", width: 464, height: 212 },
    ],
  },
  {
    id: "frameless-shower-door-bellevue",
    title: "Frameless Shower Door Installation in Bellevue, WA",
    category: "Shower Doors",
    location: "Bellevue, WA",
    completed: "April 2024",
    duration: "1 Day",
    tagline: "Modern. Clean. Custom.",
    summary: "This Bellevue homeowner upgraded an outdated bathroom with a custom frameless shower enclosure, premium hardware, and 3/8-inch tempered glass.",
    overview: "We removed the old framed shower enclosure and installed a custom frameless glass shower door with matte black hardware. The new design opened up the space, improved functionality, and gave the bathroom a modern, luxurious look.",
    benefitHeading: "Why the Customer Chose Frameless Glass",
    benefits: ["Modern, elegant look", "Makes the bathroom feel larger", "Easy to clean with minimal hardware", "Increases home value", "Custom-built for a perfect fit"],
    details: [
      { label: "Glass Type", value: "3/8-inch tempered clear glass" },
      { label: "Hardware Finish", value: "Matte black" },
      { label: "Door Style", value: "Frameless hinged door" },
      { label: "Glass Thickness", value: "3/8 inch (10 mm)" },
      { label: "Installation Type", value: "Recessed shower enclosure" },
      { label: "Warranty", value: "1-year installation warranty" },
    ],
    features: ["3/8-inch tempered safety glass", "Premium matte black hinges and handle", "Custom towel bar", "Waterproof silicone seal", "Precision measurements for a perfect fit"],
    img: "/public/projects/project_1.jpg",
    alt: "Completed frameless shower door installation in Bellevue, Washington",
    width: 624,
    height: 454,
    featured: true,
    sourceUrl: "https://eliteglassandwindow.com/elite/projects/frameless-shower-door-installation/",
    process: [
      { stage: "Before", img: "/public/projects/project_2.jpg", alt: "Bathroom shower enclosure before renovation", width: 332, height: 246 },
      { stage: "During Installation", img: "/public/projects/project_3.jpg", alt: "Frameless shower glass during installation", width: 332, height: 246 },
      { stage: "After", img: "/public/projects/project_4.jpg", alt: "Finished frameless shower door installation", width: 332, height: 246 },
    ],
    related: [
      { title: "Frameless Shower Door in Redmond, WA", img: "/public/projects/project_5.jpg", alt: "Frameless shower door project in Redmond", width: 222, height: 85 },
      { title: "Corner Shower Enclosure in Kirkland, WA", img: "/public/projects/project_6.jpg", alt: "Corner shower enclosure project in Kirkland", width: 222, height: 85 },
      { title: "Sliding Shower Door in Sammamish, WA", img: "/public/projects/project_7.jpg", alt: "Sliding shower door project in Sammamish", width: 222, height: 85 },
      { title: "Frameless Shower Door in Seattle, WA", img: "/public/projects/project_8.jpg", alt: "Frameless shower door project in Seattle", width: 222, height: 85 },
    ],
  },
  {
    id: "front-door-replacement-bothell",
    title: "Front Door Replacement in Bothell, WA",
    category: "Entry Doors",
    location: "Bothell, WA",
    completed: "March 2024",
    duration: "1 Day",
    tagline: "Simple Upgrade. Better Protection. Instant Curb Appeal.",
    summary: "We replaced an old front door with a fiberglass entry door featuring decorative glass and a modern handle set for better security, efficiency, and curb appeal.",
    overview: "The original front door was worn and outdated. We removed it and installed a new fiberglass entry door with decorative glass sidelights. This upgrade enhances the home's security, energy efficiency, and overall appearance.",
    benefitHeading: "Benefits for the Homeowner",
    benefits: ["Improved security", "Better insulation and energy efficiency", "Enhanced curb appeal", "Low maintenance and long lasting"],
    details: [
      { label: "Door Type", value: "Fiberglass front door" },
      { label: "Glass Type", value: "Decorative clear glass" },
      { label: "Color", value: "Dark gray" },
      { label: "Sidelights", value: "Yes" },
      { label: "Hardware", value: "Modern handle set" },
      { label: "Location", value: "Bothell, WA" },
      { label: "Warranty", value: "Lifetime limited warranty" },
    ],
    features: ["Fiberglass door for durability", "Decorative glass with sidelights", "Energy-efficient and secure", "Professional installation completed in one day"],
    img: "/public/projects/frontdoor_main.jpg",
    alt: "Completed fiberglass front door replacement in Bothell, Washington",
    width: 1376,
    height: 1060,
    featured: true,
    sourceUrl: "https://eliteglassandwindow.com/elite/projects/front-door-replacement/",
    process: [
      { stage: "Before", img: "/public/projects/frontdoor_before.jpg", alt: "Old front door before replacement", width: 586, height: 488 },
      { stage: "During Replacement", img: "/public/projects/frontdoor_during.jpg", alt: "Front door opening during replacement", width: 586, height: 488 },
      { stage: "After", img: "/public/projects/frontdoor_after.jpg", alt: "New fiberglass front door after installation", width: 586, height: 488 },
    ],
    related: [
      { title: "Modern Front Door Replacement in Kirkland, WA", img: "/public/projects/frontdoor_project1.jpg", alt: "Modern front door replacement in Kirkland", width: 456, height: 198 },
      { title: "Contemporary Entry Door in Bellevue, WA", img: "/public/projects/frontdoor_project2.jpg", alt: "Contemporary entry door project in Bellevue", width: 456, height: 198 },
      { title: "Front Door Replacement in Mill Creek, WA", img: "/public/projects/frontdoor_project3.jpg", alt: "Front door replacement project in Mill Creek", width: 456, height: 198 },
      { title: "Custom Wood Door Replacement in Woodinville, WA", img: "/public/projects/frontdoor_project4.jpg", alt: "Custom wood door replacement in Woodinville", width: 456, height: 198 },
    ],
  },
  {
    id: "staircase-glass-railing-medina",
    title: "Staircase Glass Railing Replacement in Medina, WA",
    category: "Glass Railings",
    location: "Medina, WA",
    completed: "May 2024",
    duration: "1 Day",
    tagline: "Modern Upgrade. Same Layout. A More Open, Elegant Space.",
    summary: "We replaced the existing wood railing with clear glass panels and stainless steel hardware while preserving the original staircase layout.",
    overview: "The homeowner wanted a more modern and open look without changing the staircase layout. We removed the existing wood railing and installed 1/2-inch tempered clear glass panels with stainless steel standoffs and a stainless steel handrail, instantly transforming the space with more light and visibility.",
    benefitHeading: "Benefits for the Homeowner",
    benefits: ["More open space and natural light", "Modern and timeless appearance", "Unobstructed views", "Increased home value", "Durable and easy to maintain"],
    details: [
      { label: "System", value: "Glass railing replacement" },
      { label: "Glass Type", value: "1/2-inch tempered clear glass" },
      { label: "Hardware", value: "Stainless steel standoffs and handrail" },
      { label: "Handrail", value: "Stainless steel round" },
      { label: "Location", value: "Interior staircase and upstairs landing" },
      { label: "Scope", value: "Railing replacement, no layout change" },
      { label: "Warranty", value: "10-year limited warranty" },
    ],
    features: ["1/2-inch tempered glass for safety", "Stainless steel standoff mounting system", "Stainless steel handrail for a clean finish", "Maintains the existing staircase layout", "Meets safety and building code requirements", "Professional installation"],
    img: "/public/projects/stair_medina_main.jpg",
    alt: "Completed staircase glass railing replacement in Medina, Washington",
    width: 1342,
    height: 932,
    featured: true,
    sourceUrl: "https://eliteglassandwindow.com/elite/projects/staircase-glass-railing-replacement/",
    process: [
      { stage: "Before: Existing Wood Railing", img: "/public/projects/stair_medina_before.jpg", alt: "Existing wood staircase railing before replacement", width: 790, height: 496 },
      { stage: "During Replacement", img: "/public/projects/stair_medina_during.jpg", alt: "Staircase railing during glass installation", width: 654, height: 412 },
      { stage: "After: New Glass Railing", img: "/public/projects/stair_medina_after.jpg", alt: "Finished clear glass staircase railing", width: 674, height: 422 },
    ],
    related: [
      { title: "Glass Railing Replacement in Bellevue, WA", img: "/public/projects/stair_project_bellevue.jpg", alt: "Glass railing replacement in Bellevue", width: 450, height: 176 },
      { title: "Staircase Glass Railing Replacement in Kirkland, WA", img: "/public/projects/stair_project_kirkland.jpg", alt: "Staircase glass railing replacement in Kirkland", width: 476, height: 172 },
      { title: "Glass Railing Replacement in Redmond, WA", img: "/public/projects/stair_project_redmond.jpg", alt: "Glass railing replacement in Redmond", width: 476, height: 180 },
      { title: "Interior Glass Railing in Sammamish, WA", img: "/public/projects/stair_project_sammamish.jpg", alt: "Interior glass railing project in Sammamish", width: 482, height: 178 },
    ],
  },
  {
    id: "window-replacement-redmond",
    title: "Window Replacement in Redmond, WA",
    category: "Windows",
    location: "Redmond, WA",
    completed: "May 2024",
    duration: "2 Days",
    tagline: "Milgard Tuscany Series - Style Line",
    summary: "We replaced 14 old vinyl windows with Milgard Tuscany Series windows to improve energy efficiency, reduce outside noise, and refresh the home's appearance.",
    overview: "These outdated, inefficient windows were difficult to open and allowed noise and drafts. We installed Milgard Tuscany Series windows with Low-E glass to improve comfort, energy efficiency, and the overall look of the home.",
    benefitHeading: "Benefits for the Homeowner",
    benefits: ["Improved energy efficiency", "Reduced outside noise", "Easier to open and clean", "Modern look that enhances curb appeal", "Increased home value"],
    details: [
      { label: "Window Brand", value: "Milgard" },
      { label: "Series", value: "Tuscany Style Line" },
      { label: "Material", value: "Vinyl" },
      { label: "Glass", value: "Low-E" },
      { label: "Interior Color", value: "White" },
      { label: "Exterior Color", value: "White" },
      { label: "Grid Style", value: "None" },
      { label: "Total Windows", value: "14" },
      { label: "Warranty", value: "Lifetime limited warranty" },
    ],
    features: ["Energy-efficient Low-E glass", "Fusion-welded frame and sash", "Smooth, easy operation", "Strong and durable vinyl frame", "Custom sized for a perfect fit", "Professional installation"],
    img: "/public/projects/window_redmond_main.jpg",
    alt: "Completed Milgard window replacement in Redmond, Washington",
    width: 1050,
    height: 688,
    featured: true,
    sourceUrl: "https://eliteglassandwindow.com/elite/projects/window-replacement/",
    process: [
      { stage: "Before", img: "/public/projects/window_redmond_before.jpg", alt: "Old vinyl windows before replacement", width: 496, height: 380 },
      { stage: "During Installation", img: "/public/projects/window_redmond_during.jpg", alt: "Home windows during replacement", width: 504, height: 382 },
      { stage: "After", img: "/public/projects/window_redmond_after.jpg", alt: "New Milgard windows after installation", width: 506, height: 376 },
    ],
    related: [
      { title: "Window Replacement in Bellevue, WA", img: "/public/projects/window_project_bellevue.jpg", alt: "Window replacement project in Bellevue", width: 370, height: 172 },
      { title: "Milgard Windows Installation in Kirkland, WA", img: "/public/projects/window_project_kirkland.jpg", alt: "Milgard window installation in Kirkland", width: 388, height: 168 },
      { title: "Whole-Home Window Replacement in Issaquah, WA", img: "/public/projects/window_project_issaquah.jpg", alt: "Whole-home window replacement in Issaquah", width: 382, height: 168 },
      { title: "Energy-Efficient Windows in Seattle, WA", img: "/public/projects/window_project_seattle.jpg", alt: "Energy-efficient window project in Seattle", width: 372, height: 166 },
    ],
  },
  {
    id: "custom-wall-mirror-kirkland",
    title: "Custom Wall Mirror Installation in Kirkland, WA",
    category: "Mirrors",
    location: "Kirkland, WA",
    completed: "April 2024",
    duration: "1 Day",
    tagline: "Custom Fit. Elegant. High Quality.",
    summary: "We custom measured, fabricated, and installed a full wall mirror with polished edges to reflect natural light and create a more open living room.",
    overview: "We installed a custom full wall mirror to enhance the living room's natural light, create an open and spacious feel, and add a modern, elegant touch. The mirror was custom cut to fit the wall perfectly with polished edges for a clean, seamless look.",
    benefitHeading: "Benefits of Wall Mirrors",
    benefits: ["Makes rooms appear larger and brighter", "Reflects natural light", "Enhances interior design", "Adds value to your home", "Custom fit for a perfect finish"],
    details: [
      { label: "Product Type", value: "Custom wall mirror" },
      { label: "Glass Type", value: "1/4-inch (6 mm) clear mirror" },
      { label: "Edges", value: "Polished" },
      { label: "Installation Type", value: "Wall mounted" },
      { label: "Size", value: "Approximately 12 ft W x 8 ft H" },
      { label: "Location", value: "Living room" },
      { label: "Warranty", value: "1-year installation warranty" },
    ],
    features: ["Custom measured for a perfect fit", "High-quality clear mirror", "Polished edges for safety and beauty", "Seamless installation", "Enhances natural light and space"],
    img: "/public/projects/mirror_kirkland_main.jpg",
    alt: "Completed custom wall mirror installation in Kirkland, Washington",
    width: 1402,
    height: 950,
    featured: true,
    sourceUrl: "https://eliteglassandwindow.com/elite/projects/custom-wall-mirror-installation/",
    process: [
      { stage: "Before", img: "/public/projects/mirror_kirkland_before.jpg", alt: "Empty living room wall before mirror installation", width: 790, height: 562 },
      { stage: "During Installation", img: "/public/projects/mirror_kirkland_during.jpg", alt: "Custom wall mirror during installation", width: 788, height: 564 },
      { stage: "After", img: "/public/projects/mirror_kirkland_after.jpg", alt: "Finished full wall mirror installation", width: 754, height: 532 },
    ],
    related: [
      { title: "Bathroom Mirror Installation in Bellevue, WA", img: "/public/projects/mirror_project_bellevue.jpg", alt: "Bathroom mirror installation in Bellevue", width: 534, height: 228 },
      { title: "Gym Wall Mirror Installation in Redmond, WA", img: "/public/projects/mirror_project_redmond.jpg", alt: "Gym wall mirror installation in Redmond", width: 540, height: 226 },
      { title: "Custom Mirror Wall in Seattle, WA", img: "/public/projects/mirror_project_seattle.jpg", alt: "Custom mirror wall project in Seattle", width: 536, height: 228 },
      { title: "Framed Bathroom Mirror in Issaquah, WA", img: "/public/projects/mirror_project_issaquah.jpg", alt: "Framed bathroom mirror project in Issaquah", width: 540, height: 230 },
    ],
  },
  {
    id: "sliding-patio-door-redmond",
    title: "Sliding Patio Door Installation in Redmond, WA",
    category: "Patio Doors",
    location: "Redmond, WA",
    completed: "May 2024",
    duration: "1 Day",
    tagline: "Smooth Operation. Modern Design. Beautiful Views.",
    summary: "We installed a premium vinyl sliding patio door with Low-E glass to add natural light, improve energy efficiency, and connect the home to its outdoor living space.",
    overview: "The homeowner wanted to upgrade their old patio door with a modern, easy-to-operate sliding door that would improve energy efficiency and provide better access to their backyard deck. We installed a premium vinyl sliding patio door with Low-E glass for maximum comfort and efficiency.",
    benefitHeading: "Benefits for the Homeowner",
    benefits: ["Smooth and easy operation", "More natural light and better views", "Improved energy efficiency", "Enhanced security features", "Increases home value"],
    details: [
      { label: "Door Type", value: "Sliding patio door" },
      { label: "Material", value: "Vinyl" },
      { label: "Brand", value: "Milgard Tuscany Series" },
      { label: "Interior Color", value: "White" },
      { label: "Exterior Color", value: "White" },
      { label: "Glass", value: "Low-E energy efficient" },
      { label: "Grid Style", value: "None" },
      { label: "Hardware", value: "Standard handle set" },
      { label: "Size", value: "72 in W x 80 in H" },
      { label: "Location", value: "Living room" },
      { label: "Warranty", value: "Lifetime limited warranty" },
    ],
    features: ["Large glass area for maximum natural light", "Low-E glass for energy efficiency", "Smooth-glide, easy-to-use system", "Strong, durable vinyl frame", "Secure multi-point lock", "Professional installation"],
    img: "/public/projects/patiodoor_redmond_main.jpg",
    alt: "Completed sliding patio door installation in Redmond, Washington",
    width: 1160,
    height: 708,
    featured: true,
    sourceUrl: "https://eliteglassandwindow.com/elite/projects/sliding-patio-door-installation/",
    process: [
      { stage: "Before", img: "/public/projects/patiodoor_redmond_before.jpg", alt: "Old sliding patio door before replacement", width: 530, height: 396 },
      { stage: "During Replacement", img: "/public/projects/patiodoor_redmond_during.jpg", alt: "Patio door opening during replacement", width: 520, height: 392 },
      { stage: "After", img: "/public/projects/patiodoor_redmond_after.jpg", alt: "New white sliding patio door after installation", width: 784, height: 596 },
    ],
    related: [
      { title: "Sliding Patio Door Installation in Bellevue, WA", img: "/public/projects/patiodoor_project_bellevue.jpg", alt: "Sliding patio door installation in Bellevue", width: 404, height: 156 },
      { title: "Multi-Slide Patio Door Installation in Kirkland, WA", img: "/public/projects/patiodoor_project_kirkland.jpg", alt: "Multi-slide patio door installation in Kirkland", width: 414, height: 156 },
      { title: "Patio Door Replacement in Issaquah, WA", img: "/public/projects/patiodoor_project_issaquah.jpg", alt: "Patio door replacement in Issaquah", width: 410, height: 160 },
      { title: "French Patio Door Installation in Sammamish, WA", img: "/public/projects/patiodoor_project_sammamish.jpg", alt: "French patio door installation in Sammamish", width: 410, height: 156 },
    ],
  },
];
